apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: olive-grove-uid      
    access: proxy
    url: http://influxdb:8086
    database: olive_grove_db
    user: admin
    secureJsonData:
      password: adminpassword
    isDefault: true